#!/bin/bash
aptitude update; aptitude safe-upgrade -y
apt install \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common -y

apt update; apt install docker docker-compose -y
